@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "admin",
    "cpf":"123.456.789-04",
    "email": "admin4@admin.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "cpf":"123.456.789-02",
    "password": "123456"
}

###

# @name create_recipient
POST {{baseUrl}}/recipients
Content-Type: application/json

{
    "name": "John Doe",
    "cpf": "123.456.789-00",
    "phone": "4799999-9999",
    "email": "johndoe@example.com",
    "address": "Address example",
    "latitude": 0,
    "longitude": 0
}

###

# @name create_package
POST {{baseUrl}}/packages
Content-Type: application/json

{
    
}

###